#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Prezto update
alias pzupdate='cd $HOME/.zprezto && git pull && git submodule update --init --recursive && cd -'

PATH="/usr/local/opt/coreutils/libexec/gnubin:$PATH"
MANPATH="/usr/local/opt/coreutils/libexec/gnuman:$MANPATH"

alias reload="source $HOME/.zshrc && echo 'ZSH config reloaded from $HOME/.zshrc'"
alias ls='ls --color=auto'

# source /usr/local/share/zsh/site-functions/_aws

# Go lang Path
export PATH=$PATH:/usr/local/opt/go/libexec/bin
export GOPATH=$HOME/work/go
export PATH=$PATH:$GOPATH/bin

# Brew and Pip aliases
alias brewski='brew update && brew upgrade --all && brew cask list | xargs brew cleanup; brew cask cleanup; brew doctor'
alias pipu='pip3 freeze --local | grep -v \'\^\-\e' | cut -d = -f 1  | xargs -n1 pip3 install -U'

# Fancy ZSH Tools
source /usr/local/share/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/local/share/zsh-navigation-tools/zsh-navigation-tools.plugin.zsh
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
export ZSH_HIGHLIGHT_HIGHLIGHTERS_DIR=/usr/local/share/zsh-syntax-highlighting/highlighters

# Setting GPG tty
export GPG_TTY=$(tty)
